In [2]:
import pandas as pd
df = pd.read_csv('./movie_data.csv')
df.head(3)

review  sentiment
0  I went to the cinema to watch a preview of thi...          0
1  Considering it's basically low-budget cast, th...          1
2  i watched this movie 10 years ago. and have wa...          1

# 8.2 BoWモデルの紹介
- テキストを数値の特徴ベクトルとして表現できるBoWモデルを紹介する。

1.ドキュメントの集合全体から、例えば単語という一意なトークンからなる語彙を作成する。

2.各ドキュメントでの各単語の出現回数を含んだ特徴ベクトルを構築する。

- 各ドキュメントにおいて一意な単語は、BoWの語彙を構成しているすべての単語の一部にすぎない。この時特徴ベクトルの大半の成分は0となるため疎ベクトルと呼ばれる。

# 8.2.1 単語を特徴ベクトルに変換する。
- BoWモデルを構築するには、scikit-learnに実装されているCountVectorizerクラスを使用できる。このクラスはテキストデータの配列を入力として、BoWモデルを自動的に生成する。

In [3]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer()#nグラム指定可能
docs = np.array(['The sun is shining',
                'The weather is sweet',
                'The sun is shining, the weather is sweet, and one and one is two'])
bag = count.fit_transform(docs)

In [4]:
#語彙はディクショナリに格納されている。
print(count.vocabulary_)

{u'and': 0, u'sun': 4, u'is': 1, u'two': 7, u'one': 2, u'weather': 8, u'sweet': 5, u'the': 6, u'shining': 3}


In [5]:
#特徴ベクトルを出力する
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


- この特徴ベクトルの各要素のインデックスは、ディクショナリの整数値に対応している。
- 特徴ベクトルの各成分はナマの出現頻度と呼ばれ、$tf(t,d)$で表さられる。これはドキュメント$d$における単語$t$の出現回数を表す。

# 8.2.2 TF-IDFを使って単語の関連性を評価する。